name: Discord Issue Notify
 
on:
  issues:
    types: [opened, closed, deleted]
 
jobs:
  notify:
    uses: cinnamobot/discord-issue-notify/.github/workflows/notify.yml@main
    secrets:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
 
